---
- name: Install prerequisite packages
  become: true
  when: ansible_facts['distribution'] != 'Amazon'
  shell: "{{ install_command }} {{ prerequisite_packages }}"

- name: Install docker
  become: true
  block:
    - name: Get docker repositories
      when: ansible_facts['distribution'] != 'Amazon'
      shell: "{{ docker.repo_command}}"
    
    - name: Install docker
      shell: "{{ install_command }} {{ docker.packages }}"

- name: Install docker-compose
  become: true
  shell: |
    curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose

- name: Start and enable docker
  become: true
  service:
    name: docker
    state: started
    enabled: true
  register: start_docker
  failed_when:
    - start_docker.failed == true

