---
- name: Rename host
  win_hostname:
    name: "{{ hostname }}"
  register: hostname_changed

- name: Reboot if hostname changed
  win_reboot:
    msg: "Rebooting to apply hostname change"
    reboot_timeout: 60
    post_reboot_delay: 90
  when: hostname_changed.changed

- name: Wait for host to come back online
  wait_for_connection:
    timeout: 300

- name: Install DNS role
  win_feature:
    name: DNS
    state: present
    include_sub_features: yes

- name: Install RSAT for DNS Management Tools
  win_feature:
    name: RSAT-DNS-Server
    state: present

- name: Install GPMC
  win_feature:
    name: GPMC
    state: present
    include_sub_features: yes

- name: Install AD Domain Services role
  win_feature:
    name: AD-Domain-Services
    state: present
    include_sub_features: yes

- name: Create forest and domain
  microsoft.ad.domain:
    create_dns_delegation: false
    dns_domain_name: "{{ domain }}"
    domain_netbios_name: "{{ netbios }}"
    domain_mode: "{{ mode }}"
    forest_mode: "{{ mode }}"
    safe_mode_password: "{{ safemodepass }}"
    install_dns: true
    reboot: true

- name: Wait for host to come back online
  wait_for_connection:
    timeout: 300

