- name: Create new Linux user  
  become: true
  user:
    name: "{{ username }}"
    state: present
    shell: /bin/bash

- name: Set user password
  become: true
  command: echo "{{ username }}:{{ password }}" | chpasswd
  when: password | length > 0

- name: Add SSH public key
  become: true
  ansible.posix.authorized_key:
    user: "{{ username }}"
    key: "{{ lookup('file', ssh_key ) }}"
    state: present
    exclusive: true

- name: Show timestamps in bash history
  become: true
  lineinfile:
    path: "/home/{{ username }}/.bashrc"
    line: 'export HISTTIMEFORMAT="%d/%m/%y %T "'
    state: present

- name: Modify sudo permissions
  when: sudo_command | length > 0
  become: true
  copy:
    content: "{{ username }} ALL=(ALL) NOPASSWD: {{ sudo_command + '\n' }}"
    dest: "/etc/sudoers.d/99-{{ username }}-user"
    owner: root
    group: root
    mode: "0600"
