---
- name: Linux domain join | Load Amazon or Ubuntu distribution variables
  ansible.builtin.include_vars: "vars/{{ ansible_facts['distribution']|lower }}.yml"
  when: ansible_facts['distribution'] in ['Ubuntu','Amazon']

- name: Linux domain join | Load SUSE distribution variables
  ansible.builtin.include_vars: "vars/sles.yml"
  when: ansible_facts['os_family'] == "Suse"

- name: Linux domain join | Load RedHat, CentOS, Oracle distribution variables
  ansible.builtin.include_vars: "vars/el.yml"
  when: ansible_facts['distribution'] in ['CentOS','OracleLinux','RedHat']