---
- name: Create user
  become: true
  ansible.builtin.user:
    name: "{{ username }}"
    create_home: yes
    password: "{{ password }}"
    update_password: always
    shell: /bin/bash

- name: Add SSH public key
  become: true
  ansible.posix.authorized_key:
    user: "{{ username }}"
    key: "{{ lookup('file', kubeuser_ssh_public_key_file ) }}"
    state: present
    exclusive: true

- name: Modify sudoers file for {{ username }}
  when: sudo_options.is_sudoer | default(false) | bool
  become: true
  copy:
    content: "{{ sudo_options.sudo_permissions + '\n' }}"
    dest: "/etc/sudoers.d/99-{{ username }}-user"
    owner: root
    group: root
    mode: 0640

- name: Create alias file for {{ username }}
  when: ( sudo_options.is_sudoer | default(false) | bool ) and sudo_options.alias_for_sudo is defined
  become: true
  blockinfile:
    create: true
    content: "{{ sudo_options.alias_for_sudo + '\n' }}"
    path: "/home/{{ username }}/.bash_profile"
    mode: 0644