---
- name: Remove existing SSM packages
  become: true
  when: ansible_facts['os_family'] != "Suse"
  package:
    name: amazon-ssm*
    state: absent
  ignore_errors: true

- name: Remove existing SSM packages (Fix for SUSE)
  become: true
  when: ansible_facts['os_family'] == "Suse"
  command: zypper remove -y amazon-ssm*

- name: Download package
  become: true
  get_url:
    url: "{{ repoURL }}"
    dest: "/tmp/{{ repoName }}"
    mode: "0644"

- name: Install Package
  become: true
  command: "{{ install_command }} /tmp/{{ repoName }}"

- name: Restart and enable SSM agent service
  become: true
  service:
    name: amazon-ssm-agent
    state: restarted
    enabled: true

- name: Remove the downloaded package
  become: true
  file:
    path: "/tmp/{{ repoName }}"
    state: absent
