---
update_command: apt update &&
install_command: apt install -y
upgrade_command: apt upgrade -y
prerequisite_packages: ca-certificates apt-transport-https gnupg2 software-properties-common
k8_repo:
  file: /etc/apt/sources.list.d/kubernetes.list
  update_repo_command: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/{{ k8_version }}/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg --yes &&
    echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ k8_version }}/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list
containerd_repo:
  file: /etc/apt/sources.list.d/docker.list
  package_name: containerd.io
  update_repo_command: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmour -o /etc/apt/trusted.gpg.d/docker.gpg --yes &&
    echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list
package_hold_command: apt-mark hold